### ISSUE TITLE
pygame window

### ISSUE THREAD

**Issue by elvodqa** [ofeksadlo/chess-cheat#14]
i can't use highlights even i changed screen resolution from main.py. when clicked on pygame window it crashes.

**Comment by ofeksadlo** [comment]
Why did you changed the resolution?
> i can't use highlights even i changed screen resolution from main.py. when clicked on pygame window it crashes.

Other than that I read you "clicked on pygame" so that's a mistake.

Try following this guidelines:
* Open up a game while logged in to lichess (Playing as anonymous will change the board size and mess everything
Also it's only tested on chrome and on 100% zoom while logged in).
* During the freeze time open up the program choose your starting color. And alt+tab back to the browser (Don't use your mouse).
Keep in mind that your mouse clicks from that moment matters.
So play like that: 1 click represent the from cell and 1 click represent the to cell when it's your turn.
No dragging pieces.
No checking youtube for a second
It will mess everything and the program will crash

Keep in mind lichess would most definetly ban you for playing against other players.
Play only against bots!

**Comment by elvodqa** [comment]
ok thanks
